apiVersion: apps/v1
kind: Deployment

metadata:
  name: college-event

spec:
  replicas: 3

  selector:
    matchLabels:
      app: college-event

  template:
    metadata:
      labels:
        app: college-event

    spec:
      containers:
      - name: college-event
      
        image: events:v1
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8080